# Generated by Django 2.1.15 on 2022-05-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default=1, upload_to='files/image/news_img/%Y-%m-%d/'),
            preserve_default=False,
        ),
    ]
