# Generated by Django 2.1.15 on 2022-05-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default=1, max_length=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='count_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(default=1, max_length=99),
            preserve_default=False,
        ),
    ]
