# Generated by Django 2.1.15 on 2022-05-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_email', models.EmailField(default=None, max_length=254)),
                ('person_telephone', models.CharField(default=None, max_length=99)),
                ('name_org', models.CharField(max_length=99)),
                ('logo_org', models.ImageField(upload_to='files/image/org_logo_request/%Y-%m-%d/')),
                ('address', models.CharField(max_length=199)),
                ('type_org', models.CharField(max_length=99)),
                ('description', models.CharField(max_length=999)),
                ('is_pull', models.BooleanField(default=False)),
                ('date_created_request', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonPullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('role', models.CharField(max_length=99)),
                ('description', models.CharField(max_length=999)),
                ('date_created_request', models.DateField(auto_now=True)),
            ],
        ),
    ]
