# Generated by Django 2.1.15 on 2022-05-29 21:43

import auth_person.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=99)),
                ('bio', models.CharField(blank=True, max_length=160, null=True)),
                ('name', models.CharField(blank=True, max_length=99, null=True)),
                ('surname', models.CharField(blank=True, max_length=99, null=True)),
                ('ndName', models.CharField(blank=True, max_length=99, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='files/image/user_logo/%Y-%m-%d/')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('balance', models.DecimalField(decimal_places=10, max_digits=19)),
                ('registrationDate', models.DateTimeField(auto_now=True)),
                ('lastEntrance', models.DateTimeField(auto_now=True)),
                ('is_organizate', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=99)),
                ('address', models.CharField(max_length=999)),
                ('translate', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', auth_person.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmen_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MembershipDepartmentId', to='auth_person.Department')),
                ('PersonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MembershipPersonId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('type', models.CharField(max_length=99)),
                ('description', models.CharField(max_length=999)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='files/image/org_logo/%Y-%m-%d/')),
                ('address', models.CharField(max_length=199)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=12, unique=True)),
                ('secret_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PersonSpecs',
            fields=[
                ('personSpecs_id', models.AutoField(primary_key=True, serialize=False)),
                ('PersonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonSpecsPersonId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='personspecs',
            name='SpecId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonSpecsSpecId', to='auth_person.Specialization'),
        ),
        migrations.AddField(
            model_name='person',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toCardFromUser', to='auth_person.PersonCard'),
        ),
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_person.Role'),
        ),
        migrations.AddField(
            model_name='person',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
