# Generated by Django 2.1.15 on 2022-05-10 11:16

import auth_person.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.CharField(blank=True, max_length=160, null=True)),
                ('balance', models.DecimalField(decimal_places=10, max_digits=19)),
                ('registrationDate', models.DateTimeField(auto_now=True)),
                ('lastEntrance', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', auth_person.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmen_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('logo_id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='files/image/user_logo/%Y-%m-%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MembershipDepartmentId', to='auth_person.Department')),
                ('PersonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MembershipPersonId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('mPhone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonBirthday',
            fields=[
                ('birthday_id', models.AutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=12, unique=True)),
                ('secret_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PersonLogin',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(help_text='basic login information', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('name_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonNdName',
            fields=[
                ('ndName_id', models.AutoField(primary_key=True, serialize=False)),
                ('ndName', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonSpecs',
            fields=[
                ('personSpecs_id', models.AutoField(primary_key=True, serialize=False)),
                ('PersonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonSpecsPersonId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonSurname',
            fields=[
                ('surname_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='personspecs',
            name='SpecId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonSpecsSpecId', to='auth_person.Specialization'),
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toBurthdayFromUser', to='auth_person.PersonBirthday'),
        ),
        migrations.AddField(
            model_name='person',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toCardFromUser', to='auth_person.PersonCard'),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='toEmailFromUser', to='auth_person.Email', unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='person',
            name='logoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toLogoFromUser', to='auth_person.Logo'),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toNameFromUser', to='auth_person.PersonName'),
        ),
        migrations.AddField(
            model_name='person',
            name='ndName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toNdNameFromUser', to='auth_person.PersonNdName'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toPhoneFromUser', to='auth_person.MobilePhone'),
        ),
        migrations.AddField(
            model_name='person',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_person.Role'),
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toSurnameFromUser', to='auth_person.PersonSurname'),
        ),
        migrations.AddField(
            model_name='person',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toLoginFromUser', to='auth_person.PersonLogin'),
        ),
    ]
