# Generated by Django 4.0.2 on 2022-02-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmen_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('logo_id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.FileField(upload_to='files/image/user_logo/%Y-%m-%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(help_text='basic login information', max_length=20, unique=True)),
                ('password', models.CharField(help_text='basic login information', max_length=32, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('ndName', models.CharField(blank=True, max_length=30, null=True)),
                ('birthday', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=10, max_digits=19)),
                ('registrationDate', models.DateTimeField(auto_now=True)),
                ('lastEntrance', models.DateTimeField(auto_now=True)),
                ('logoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_person.logo')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PersonSpecs',
            fields=[
                ('personSpecs_id', models.AutoField(primary_key=True, serialize=False)),
                ('PersonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonSpecsPersonId', to='auth_person.person')),
                ('SpecId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonSpecsSpecId', to='auth_person.specialization')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_person.role'),
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('mPhone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MembershipDepartmentId', to='auth_person.department')),
                ('PersonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MembershipPersonId', to='auth_person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailPerson', to='auth_person.person')),
            ],
        ),
    ]
