# Generated by Django 4.0.2 on 2022-02-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.FileField(null=True, upload_to='files/image/user_logo/%Y-%m-%d/'),
        ),
    ]
