# Generated by Django 2.1.15 on 2022-05-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_organizate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='organization_name',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='type_activity',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
