# Generated by Django 2.1.15 on 2022-05-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
