# Generated by Django 2.1.15 on 2022-05-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0002_person_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
