# Generated by Django 4.0.2 on 2022-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0002_alter_logo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(null=True, upload_to='files/image/user_logo/%Y-%m-%d/'),
        ),
    ]
