# Generated by Django 4.0.2 on 2022-02-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0003_alter_logo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='files/image/user_logo/%Y-%m-%d/'),
        ),
    ]
