# Generated by Django 4.0.2 on 2022-03-04 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0004_alter_logo_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='personId',
        ),
        migrations.RemoveField(
            model_name='mobilephone',
            name='personId',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_person.email'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_person.mobilephone'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='logoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_person.logo'),
        ),
    ]
