# Generated by Django 4.0.2 on 2022-03-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0005_remove_email_personid_remove_mobilephone_personid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toEmailFromUser', to='auth_person.email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='logoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toLogoFromUser', to='auth_person.logo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toPhoneFromUser', to='auth_person.mobilephone'),
        ),
    ]
