# Generated by Django 4.0 on 2022-03-03 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0005_remove_email_personid_remove_mobilephone_personid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_person.email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='logoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_person.logo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_person.mobilephone'),
        ),
    ]
