# Generated by Django 2.1.15 on 2022-06-01 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0005_auto_20220601_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='organizated',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth_person.Organization'),
        ),
    ]
