# Generated by Django 4.0.2 on 2022-03-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0006_alter_person_email_alter_person_logoid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=12, unique=True)),
                ('secret_code', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toCardFromUser', to='auth_person.personcard'),
        ),
    ]
