# Generated by Django 2.1.15 on 2022-06-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0007_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
