# Generated by Django 2.1.15 on 2022-06-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0008_person_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personspecs',
            name='PersonId',
        ),
        migrations.RemoveField(
            model_name='personspecs',
            name='SpecId',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='address',
            new_name='address_org',
        ),
        migrations.AddField(
            model_name='person',
            name='specialization',
            field=models.CharField(default=0, max_length=999),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PersonSpecs',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
