# Generated by Django 2.1.15 on 2022-06-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0009_auto_20220601_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
