# Generated by Django 4.0.2 on 2022-03-22 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0012_alter_person_card_alter_personcard_secret_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toCardFromUser', to='auth_person.personcard'),
        ),
        migrations.AlterField(
            model_name='personcard',
            name='secret_code',
            field=models.CharField(max_length=3),
        ),
    ]
