# Generated by Django 4.0.2 on 2022-04-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_person', '0015_remove_membership_departmentid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmen_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('logo_id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='files/image/user_logo/%Y-%m-%d/')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('mPhone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=10, max_digits=19)),
                ('registrationDate', models.DateTimeField(auto_now=True)),
                ('lastEntrance', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonBirthday',
            fields=[
                ('birthday_id', models.AutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=12, unique=True)),
                ('secret_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PersonLogin',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(help_text='basic login information', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('name_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonNdName',
            fields=[
                ('ndName_id', models.AutoField(primary_key=True, serialize=False)),
                ('ndName', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonPassword',
            fields=[
                ('password_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='basic login information', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PersonSurname',
            fields=[
                ('surname_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PersonSpecs',
            fields=[
                ('personSpecs_id', models.AutoField(primary_key=True, serialize=False)),
                ('PersonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonSpecsPersonId', to='auth_person.person')),
                ('SpecId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonSpecsSpecId', to='auth_person.specialization')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toBurthdayFromUser', to='auth_person.personbirthday'),
        ),
        migrations.AddField(
            model_name='person',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toCardFromUser', to='auth_person.personcard'),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toEmailFromUser', to='auth_person.email'),
        ),
        migrations.AddField(
            model_name='person',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toLoginFromUser', to='auth_person.personlogin'),
        ),
        migrations.AddField(
            model_name='person',
            name='logoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toLogoFromUser', to='auth_person.logo'),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toNameFromUser', to='auth_person.personname'),
        ),
        migrations.AddField(
            model_name='person',
            name='ndName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toNdNameFromUser', to='auth_person.personndname'),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toPasswordFromUser', to='auth_person.personpassword'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toPhoneFromUser', to='auth_person.mobilephone'),
        ),
        migrations.AddField(
            model_name='person',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_person.role'),
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toSurnameFromUser', to='auth_person.personsurname'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MembershipDepartmentId', to='auth_person.department')),
                ('PersonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MembershipPersonId', to='auth_person.person')),
            ],
        ),
    ]
