# Generated by Django 4.0.2 on 2022-04-04 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0017_alter_email_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toPhoneFromUser', to='auth_person.mobilephone'),
        ),
    ]
