# Generated by Django 4.0.2 on 2022-03-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_person', '0006_alter_person_email_alter_person_logoid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.DecimalField(decimal_places=10, max_digits=19)),
                ('tDate', models.DateTimeField()),
                ('recipientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipient', to='auth_person.person')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='auth_person.person')),
            ],
        ),
    ]
