# Generated by Django 4.0.2 on 2022-04-03 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_person', '0016_initial'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='recipientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='auth_person.person'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='senderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='auth_person.person'),
        ),
    ]
