# Generated by Django 2.1.15 on 2022-05-30 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_product', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('summary', models.DecimalField(decimal_places=10, max_digits=19)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('type', models.CharField(max_length=99)),
                ('img', models.ImageField(upload_to='files/image/product_img/%Y-%m-%d/')),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Product'),
        ),
    ]
