# Generated by Django 2.1.15 on 2022-05-11 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=4000, null=True)),
                ('taskData', models.FileField(upload_to='')),
                ('payment', models.DecimalField(decimal_places=10, max_digits=19)),
                ('startDate', models.DateTimeField()),
                ('finishDate', models.DateTimeField()),
                ('customerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaskCustomer', to=settings.AUTH_USER_MODEL)),
                ('implementerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskImplementer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
