# Generated by Django 2.1.15 on 2022-05-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskData',
            field=models.FileField(blank=True, null=True, upload_to='files/file_work/work/%Y-%m-%d/'),
        ),
    ]
