# Generated by Django 2.1.15 on 2022-05-31 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_auto_20220513_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('duration', models.DurationField()),
                ('finishDate', models.DateField()),
                ('description', models.CharField(max_length=999)),
                ('location', models.CharField(max_length=99)),
                ('img', models.ImageField(upload_to='files/event_img/event/%Y-%m-%d/')),
                ('caster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
