# Generated by Django 2.1.15 on 2022-06-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_goingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
