# Generated by Django 2.1.15 on 2022-06-01 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('pas', models.BooleanField(default=False)),
                ('booking', models.BooleanField(default=False)),
                ('costPerHour', models.DecimalField(decimal_places=10, max_digits=19)),
                ('img', models.ImageField(upload_to='files/machine_img/%Y-%m-%d/')),
            ],
        ),
        migrations.CreateModel(
            name='MachineBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('bookingDate', models.DateField()),
                ('MachineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MachineBookingMachineId', to='machine.Machine')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MachineBookingPersonId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
